config/routes.rb
Mrenglish::Application.routes.draw do

  resources :study_groups do
	  resources :bookings
	end
  devise_for :teachers, :controllers => { :registrations => 'registrations' }
  devise_for :students, :controllers => { :registrations => 'registrations' }
  resources :users, only: [:index]
  root "pages#home"

  get "/home" , to: "pages#home", as: "home"
  get "about" => 'pages#about'
  get "contact" => 'pages#contact'
  get "students" => 'students#index'

end

app/models/study_group.rb
class StudyGroup < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :bookings
end

app/controllers/study_groups_controller.rb
class StudyGroupsController < ApplicationController

  def index
    @study_groups = StudyGroup.all
  end

  def new
    @study_group = StudyGroup.new
  end

  def create
    @study_group = StudyGroup.create(study_group_params)
    if @study_group.save
      name = @study_group.name
      redirect_to study_groups_path
      flash[:notice] = "#{name} created"
    else
      render 'new'
      flash[:error] = "Unable to create study group. Please try again"
    end
  end

  def destroy
    @study_group = StudyGroup.find(params[:id])
    @study_group.destroy
    redirect_to study_groups_path
  end

  def edit
    @study_group = StudyGroup.find(params[:id])
  end

  def update
    @study_group = StudyGroup.find(params[:id])
    @study_group.update study_group_params
    if @study_group.save
      flash[:notice] = "Your study group was updated succesfully"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private

    def study_group_params
      params.require(:study_group).permit(:name, :delete)
    end

end

app/views/study_groups/_errors.html.erb
<% if @study_group.errors.any? %>
  <div class="errors">
    <h3>
      <%= pluralize(@study_group.errors.count, 'error') %>
      prohibited this study_group from being saved:
    </h3>
    <ul>
      <% @study_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/study_groups/_form.html.erb
<%= form_for @study_group do |f| %>
  <%= render 'errors' %>
  <%= f.label 'name', 'Name' %>
  <%= f.text_field 'name', placeholder: 'Name'%>
  <%= f.submit 'Submit' %>
<% end %>

app/views/study_groups/edit.html.erb
<%= render 'form' %>

app/views/study_groups/index.html.erb
<h3>study groups</h3>

<% @study_groups.each do |study_group| %>
  <div class="study_group">
    <%= study_group.name %>
    <%= link_to "Show all bookings", study_group_bookings_path(study_group) %>
    <%= link_to "Delete", study_group_path(study_group), data: { confirm: 'Are you sure?' }, method: :delete %>
    <%= link_to "Edit", edit_study_group_path(study_group) %>
    <%= link_to "Add booking", new_study_group_booking_path(study_group) %>
  </div>
<% end %>

app/views/study_groups/new.html.erb
<%= render 'form' %>