config/routes.rb
Mrenglish::Application.routes.draw do

  resources :study_groups do
	  resources :bookings
	end
  devise_for :teachers, :controllers => { :registrations => 'registrations' }
  devise_for :students, :controllers => { :registrations => 'registrations' }
  resources :users, only: [:index]
  root "pages#home"

  get "/home" , to: "pages#home", as: "home"
  get "about" => 'pages#about'
  get "contact" => 'pages#contact'
  get "students" => 'students#index'

end

app/models/booking.rb
require_relative './concerns/bookable'

class Booking < ActiveRecord::Base
  include Bookable
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  respond_to :html, :xml, :json
  
  before_action :find_study_group

  def index
    @bookings = Booking.where("study_group_id = ? AND end_time >= ?", @study_group.id, Time.now).order(:start_time)
    respond_with @bookings
  end

  def new
    @booking = Booking.new(study_group_id: @study_group.id)
  end

  def create
    @booking =  Booking.new(params[:booking].permit(:study_group_id, :start_time, :length))
    @booking.study_group = @study_group
    if @booking.save
      redirect_to study_group_bookings_path(@study_group, method: :get)
    else
      render 'new'
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def destroy
    @booking = Booking.find(params[:id]).destroy
    if @booking.destroy
      flash[:notice] = "Booking: #{@booking.start_time.strftime('%e %b %Y %H:%M%p')} to #{@booking.end_time.strftime('%e %b %Y %H:%M%p')} deleted"
      redirect_to study_group_bookings_path(@study_group)
    else
      render 'index'
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    # @booking.study_group = @study_group

    if @booking.update(params[:booking].permit(:study_group_id, :start_time, :length))
      flash[:notice] = 'Your booking was updated succesfully'

      if request.xhr?
        render json: {status: :success}.to_json
      else
        redirect_to study_group_bookings_path(@study_group)
      end
    else
      render 'edit'
    end
  end

  private

  def save booking
    if @booking.save
        flash[:notice] = 'booking added'
        redirect_to study_group_booking_path(@study_group, @booking)
      else
        render 'new'
      end
  end

  def find_study_group
    if params[:study_group_id]
      @study_group = StudyGroup.find_by_id(params[:study_group_id])
    end
  end

end

app/views/bookings/_errors.html.erb
<% if @booking.errors.any? %>
  <div class="errors">
    <h3><%= pluralize(@booking.errors.count, 'error') %>
      prohibited this booking from being saved:
    </h3>
    <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/bookings/_form.html.erb
<%= form_for([@study_group, @booking]) do |f| %>
  <p>
    <%= f.label 'start_time', 'Start time' %>
    <%= f.datetime_select :start_time, { minute_step: 15 } %>
  </p>
  <p>
    <%= f.label 'length', 'Length of booking in hours' %>
    <%= f.number_field 'length', min: 1 %>
  </p>
  <%= f.submit 'Submit' %>
<% end %> 

app/views/bookings/edit.html.erb
<h3>Edit booking for <%= @study_group.name %></h3>

<%= render 'errors' %>
<%= render 'form' %>

<div class="calendar_container">
  <div id="calendar">
  </div>
</div>

app/views/bookings/index.html.erb
<h3> Bookings for <%= @study_group.name %></h3>
<table class="bookings_table">
  <tr>
    <th>Start</th>
    <th>End</th>
  </tr>
  
  <% @bookings.each do |booking| %>
  <tr>
    <td>
      <%= booking.start_time.strftime('%e %b %Y %H:%M%p') %>
    </td>
    <td>
      <%= (booking.calculate_end_time + 60).strftime('%e %b %Y %H:%M%p') %>
    </td>
    <td><%= link_to "Delete", study_group_booking_path(@study_group, booking), data: { confirm: 'Are you sure?' }, method: :delete %>
    </td>
    <td><%= link_to "Edit", edit_study_group_booking_path(@study_group, booking) %>
    </td>
  </tr>
  <% end %>
</table>

app/views/bookings/new.html.erb
<h3>Add booking for <%= @study_group.name %></h3>
  
<%= render 'errors' %>
<%= render 'form' %> 

<div class="calendar_container">
  <div id="calendar">
  </div>
</div>

app/views/bookings/show.html.erb
<h3>Booking Confirmation</h3>
<p>Your booking is confirmed for
  <%= @study_group.name %>:
  <%= @booking.start_time.strftime('%e %b %Y %H:%M%p') %>
  until
  <%= (@booking.calculate_end_time + 60).strftime('%e %b %Y %H:%M%p') %>