config/routes.rb
Mrenglish::Application.routes.draw do

  resources :study_groups do
	  resources :bookings
	end
  devise_for :teachers, :controllers => { :registrations => 'registrations' }
  devise_for :students, :controllers => { :registrations => 'registrations' }
  resources :users, only: [:index]
  root "pages#home"

  get "/home" , to: "pages#home", as: "home"
  get "about" => 'pages#about'
  get "contact" => 'pages#contact'
  get "students" => 'students#index'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Mr. English</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Contact', contact_path %></li>
        <% if student_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Edit Profile', edit_student_registration_path %></li>
              <li><a href="#">Book a Lesson</a></li>
              <li><a href="#">My lessons</a></li>
              <li class="divider"></li>
              <li><%= link_to 'Sign Out', destroy_student_session_path, method: :delete %></li>
            </ul>
          </li>

        <% elsif teacher_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Edit Profile', edit_teacher_registration_path %></li>
              <li><a href="#">Lessons</a></li>
              <li><a href="#">Calendar</a></li>
              <li><a href="#">Students</a></li>
              <li class="divider"></li>
              <li><%= link_to 'Sign Out', destroy_teacher_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Sign Up', new_student_registration_path %></li>
          <li><%= link_to 'Sign In', new_student_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_headerImage.html.erb
<div class="skinnify">
	<!-- <img src="/assets/images/mr-english-kochi-eikaiwa.jpg" alt="Kochi Eikaiwa Mr. English" title="Mr. English Kochi Eikaiwa harimaya bashi"/> -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mrenglish</title>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>

  <!-- Latest compiled and minified JavaScript -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <!-- Latest compiled and minified JQuery -->
 <script src="//code.jquery.com/jquery-2.1.1.min.js"></script>
</head>
<body>

<div class="container">
	<%= render 'layouts/headerImage' %>
	<%= render 'layouts/header' %>

	<% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %> 

	<%= yield %>
</div>

</body>
</html>